baseURL = "/"
languageCode = "en-us"
title = "Pudenda"
relativeUrls = true
theme = "reveal-hugo"

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true
