baseURL = "/"
languageCode = "en-us"
title = "Pudenda"
theme = "reveal-hugo"
relativeUrls = true


[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true
